export default {
  ignores: [
    "app-example/*",
    "node_modules/*",
    "./expo-env.d.ts",
    "**/*.snap",
    ".env*",
    ".gitignore",
    "yarn.lock",
    "tsconfig.json",
    ".lintstagedrc.json",
    "dist/*",
    "android/*",
    "ios/*",
    "coverage/*",
    ".expo/*",
    "metro.config.js",
    "jest.config.js",
    "eslint.config.mjs",
    "eslint/**/*",
  ],
};
