#!/bin/bash

# Ensure the script exits if any command fails
set -e

echo "Creating .env file..."

# Create or overwrite the .env file
# List the names of the secrets you expect.
# These will be available as uppercase environment variables.
echo "EXPO_PUBLIC_PROJECT_WEBSITE_URL=${EXPO_PUBLIC_PROJECT_WEBSITE_URL}" > .env
{
  echo "EXPO_PUBLIC_SENTRY_ORGANIZATION=${EXPO_PUBLIC_SENTRY_ORGANIZATION}"
  echo "EXPO_PUBLIC_SENTRY_PROJECT=${EXPO_PUBLIC_SENTRY_PROJECT}"
  echo "EXPO_PUBLIC_SENTRY_DSN=${EXPO_PUBLIC_SENTRY_DSN}"
  echo "EXPO_PUBLIC_SENTRY_URL=${EXPO_PUBLIC_SENTRY_URL}"
  echo "EXPO_PUBLIC_SENTRY_ENVIRONMENT=${EXPO_PUBLIC_SENTRY_ENVIRONMENT}"
  echo "EXPO_PUBLIC_SENTRY_TRACES_SAMPLER=${EXPO_PUBLIC_SENTRY_TRACES_SAMPLER}"
  echo "EXPO_PUBLIC_PROFILES_SAMPLE_RATE=${EXPO_PUBLIC_PROFILES_SAMPLE_RATE}"
  echo "EXPO_PUBLIC_SENTRY_ENABLED=${EXPO_PUBLIC_SENTRY_ENABLED}"
  echo "EXPO_PUBLIC_SENTRY_AUTH_TOKEN=${EXPO_PUBLIC_SENTRY_AUTH_TOKEN}"
  echo "EXPO_PUBLIC_SUPABASE_URL=${EXPO_PUBLIC_SUPABASE_URL}"
  echo "EXPO_PUBLIC_SUPABASE_ANON_KEY=${EXPO_PUBLIC_SUPABASE_ANON_KEY}"
  echo "EXPO_PUBLIC_IOS_URL_SCHEME=${EXPO_PUBLIC_IOS_URL_SCHEME}"
  echo "EXPO_PUBLIC_GOOGLE_SIGN_IN_WEB_CLIENT_ID=${EXPO_PUBLIC_GOOGLE_SIGN_IN_WEB_CLIENT_ID}"
  echo "EXPO_PUBLIC_GOOGLE_SIGN_IN_IOS_CLIENT_ID=${EXPO_PUBLIC_GOOGLE_SIGN_IN_IOS_CLIENT_ID}"
} >> .env

# Add more secrets as needed

echo ".env file created successfully."

# Optional: You might want to restrict permissions on the .env file
# chmod 600 .env
